name: ml-lecture

channels:
  - defaults

dependencies:
  - python=3.7
  - graphviz=2.40
  - ipython=7
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib=3
  - notebook=5.7
  - numpy=1.18
  - pandas=1
  - pip
  - pydotplus=2
  - pytables
  - pytables=3.5
  - python-graphviz=0.8
  - scikit-learn=0.23
  - scipy=1.4
  - seaborn=0.10
  - tqdm
  - xlrd>=1
  - pip:
    - jupyter_contrib_nbextensions
