name: ml

channels:
  - defaults

dependencies:
  - python=3.8
  - graphviz=2
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - conda-forge::matplotlib=3.4
  - notebook
  - numpy=1.20
  - pandas
  - pip
  - pydotplus
  - pytables
  - h5py
  - python-graphviz
  - scikit-image
  - scikit-learn=0.24
  - scipy=1.6
  - seaborn
  - tqdm
  - xlrd>=1
  - pillow
  - pip:
    - jupyter_contrib_nbextensions
    - pyfact
